language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"

matrix:
  include:
    - python: 2.7
      env: BUILDMODE=CONDA
    - python: 2.7
      env: BUILDMODE=CIBUILDWHEEL
      sudo: required
      services:
        - docker
    - python: 3.5
      env: BUILDMODE=CONDA
    - python: 3.6
      env: BUILDMODE=CONDA
    - os: osx
      language: generic
      env: BUILDMODE=CIBUILDWHEEL

env:
  global:
    - HYPOTHESIS_PROFILE=ci

install:
  - source ci/travis-install.sh

script:
  - source ci/travis-build.sh
