jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python2.7:
        python_version: '2.7'
      Python3.5:
        python_version: '3.5'
      Python3.6:
        python_version: '3.6'
      Python3.7:
        python_version: '3.7'

  variables:
    # Enable fuzzing tests, other expensive tests.
    ZSTD_SLOW_TESTS: '1'

    # Make all compile warnings fatal.
    ZSTD_WARNINGS_AS_ERRORS: '1'

    # More thorough fuzzing coverage.
    HYPOTHESIS_PROFILE: ci

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name env python=$PYTHON_VERSION
    displayName: Create Anaconda environment

  - bash: |
      source activate env
      conda install --yes --quiet --name env conda-build pip
      pip install --require-hashes -r ci/requirements.txt
    displayName: Install dependencies

  - bash: |
      source activate env
      conda build ci/conda
      python ci/copy-conda-package.py
    displayName: Build and Test

  - task: PublishPipelineArtifact@1
    inputs:
      path: $(System.DefaultWorkingDirectory)/dist
