on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  schedule:
    - cron: '30 13 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: { }
jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        py:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    runs-on: 'ubuntu-24.04'
    env:
      # Enable fuzzing tests, other expensive tests.
      ZSTD_SLOW_TESTS: '1'
      # Make all compile warnings fatal.
      ZSTD_WARNINGS_AS_ERRORS: '1'
      # More thorough fuzzing coverage.
      HYPOTHESIS_PROFILE: 'ci'
    steps:
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.py }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Miniconda and Create Environment
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          activate-environment: env
          python-version: "${{ matrix.py }}"
          channels: conda-forge,defaults

      - name: Install Dependencies
        run: |
          conda install --yes --quiet --name base conda-build
          conda install --yes --quiet --name env pip
          pip install --require-hashes -r ci/requirements.txt

      - name: Build and Test
        run: |
          conda build ci/conda
          python ci/copy-conda-package.py

      - name: Upload Package
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: linux-${{ matrix.py }}
          path: dist

  windows:
    strategy:
      fail-fast: false
      matrix:
        py:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    runs-on: 'windows-2022'
    env:
      # Enable fuzzing tests, other expensive tests.
      ZSTD_SLOW_TESTS: '1'
      # Make all compile warnings fatal.
      ZSTD_WARNINGS_AS_ERRORS: '1'
      # More thorough fuzzing coverage.
      HYPOTHESIS_PROFILE: 'ci'
    steps:
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.py }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Miniconda and Create Environment
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          activate-environment: env
          python-version: "${{ matrix.py }}"
          channels: conda-forge,defaults

      - name: Install Dependencies
        run: |
          conda install --yes --quiet --name base conda-build
          conda install --yes --quiet --name env pip
          python -m pip install --user --require-hashes -r ci/requirements.txt

      - name: Build and Test
        run: |
          conda build ci/conda
          python ci/copy-conda-package.py

      - name: Upload Package
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: windows-${{ matrix.py }}
          path: dist
